---
- name: Clone repository by ghq
  register: sync_results
  command: ghq get -u "{{ item.repo }}"
  changed_when: "'Already up-to-date.' not in sync_results.stdout"
  with_items:
    - "{{ ghq_repos }}"
    - "{{ ghq_private_repos }}"
- name: Clone Github repository
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ git_repos }}"
    - "{{ git_private_repos }}"
