---
- name: Setup MacOS
  hosts: localhost_darwin
  connection: local
  roles:
    - role: homebrew
      tags:
        - homebrew
    - role: macos/osx_defaults
      tags:
        - osx_defaults
    - role: go
      tags:
        - go
