---
- name: Setup MacOS
  hosts: localhost_darwin
  connection: local
  roles:
    - role: common
      tags:
        - common
    - role: williamyeh.oracle-java
      tags:
        - java
    - role: homebrew
      tags:
        - homebrew
    - role: macos/osx_defaults
      tags:
        - osx_defaults
    - role: python
      tags:
        - python
    - role: ruby
      tags:
        - ruby
    - role: atom_pkg
      tags:
        - atom_pkg
    - role: yadm
      tags:
        - yadm
    - role: go
      tags:
        - go
    - role: repos
      tags:
        - repos
    - role: macos
      tags:
        - macos
