---
- name: Setup MacOS
  hosts: localhost_darwin
  connection: local
  roles:
    - role: homebrew
      tags:
        - homebrew
    - role: macos/osx_defaults
      tags:
        - osx_defaults
    - role: gvm
      tags:
        - gvm
    - role: atom_pkg
      tags:
        - atom_pkg
    - role: yadm
      tags:
        - yadm
