---
- include_vars: global_domain.yml
- include_vars: kotoeri.yml
- include_vars: dock.yml
- include_vars: finder.yml
- include_vars: safari.yml
- include_vars: image_capture.yml

- name: "Ensure macOS defaults"
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  notify:
    - Restart Finder
    - Restart Dock
    - Restart JapaneseIM
  with_items:
    - "{{ global_domain.plist }}"
    - "{{ kotoeri.plist }}"
    - "{{ dock.plist }}"
    - "{{ finder.plist }}"
    - "{{ safari.plist }}"
    - "{{ image_capture.plist }}"
