---
- include_vars: darwin.yml
  when: ansible_os_family == "Darwin"
- include_vars: linux.yml
  when: ansible_os_family == "Linux"

- name: Install packages by pip
  pip:
    name: "{{ item.name }}"
    state: latest
    extra_args: "{{ pip_common_extra_args }} {{ item.extra_args | default('') }}"
  with_items: "{{ pip_packages }}"
  environment:
    # Disabled for installing global packages on site.USR_SITE
    PIP_REQUIRE_VIRTUALENV: ''
- name: Ensure pip config directory
  file:
    path: "{{ pip_config_dir }}"
    state: directory
    recurse: yes
- name: Copy pip.conf
  copy:
    src: files/pip/pip.conf
    dest: "{{ pip_config_dir }}/pip.conf"
