---
- name: Launch locate
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
  register: result
  become: true
  become_method: sudo
  changed_when: '"" == result.stderr'
- name: Install stree command
  command: ln -s /Applications/SourceTree.app/Contents/Resources/stree /usr/local/bin/stree
  args:
    creates: /usr/local/bin/stree
