---
- name: Launch locate
  command: launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
  register: result
  become: true
  become_method: sudo
  changed_when: '"" == result.stderr'
- name: "Create symlinks"
  command: ln -s "{{ item.source }}" "{{ item.target }}"
  args:
    creates: "{{ item.target }}"
  with_items: "{{ symlinks }}"
- name: Find xcode-themes
  register: theme_result
  command: ghq list -p xcode-themes
  changed_when: false
- name: Install xcode-themes
  command: ./install.sh
  when: "'xcode-themes' in theme_result.stdout"
  args:
    chdir: "{{ theme_result.stdout }}"
    creates: "{{ ansible_user_dir }}/Library/Developer/Xcode/UserData/FontAndColorThemes"
