---
- name: Ensure goenv directories
  file:
    path: "{{ item.name }}"
    state: directory
    recurse: yes
  with_items: "{{ goenv_dirs }}"
- name: Install goenv
  shell: |
    bash -cl 'curl -L https://bitbucket.org/ymotongpoo/goenv/raw/master/shellscripts/fast-install.sh | zsh && mv goenv "{{ goenvroot }}"'
  args:
    creates: "{{ goenvtarget }}/goenv"
  environment:
    GOENVTARGET: "{{ goenvtarget }}"
- name: Install go packages
  shell: |
    bash -cl 'go get -u "{{ item.name }}"'
  with_items: "{{ go_packages }}"
- name: Install gometalinter
  shell: |
    bash -cl 'gometalinter --install --update'
