---
- name: Check installed GVM
  register: result
  ignore_errors: True
  shell: |
    bash -cl 'gvm list >/dev/null'
  failed_when: "'command not found' in result.stderr"
  changed_when: "result.rc != 0"
- name: Install GVM
  shell: |
    bash -cl 'bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)'
  when: result|failed
- name: Update GVM
  register: update_result
  shell: |
    bash -cl 'gvm get'
  changed_when: "'up-to-date' not in update_result.stdout"
- name: Check if System Go is installed
  shell: |
    bash -cl 'gvm list | grep system'
  changed_when: False
- name: Check if System Go is used by GVM
  register: use_system_go
  ignore_errors: True
  shell: |
    bash -cl 'gvm list | grep system | grep "=>"'
  changed_when: "use_system_go.rc != 0"
- name: Select System Golang
  shell: |
    bash -cl 'gvm use system --default'
  when: use_system_go|failed
- name: Install go packages
  shell: |
    bash -cl 'go get "{{ item.name }}"'
  with_items: "{{ go_packages }}"
- name: Install gometalinter
  shell: |
    bash -cl 'gometalinter --install --update'
