---
go_packages:
  - name: github.com/typester/gh-open
  - name: github.com/nsf/gocode
  - name: github.com/golang/lint/golint
  - name: github.com/rogpeppe/godef
  - name: github.com/kisielk/errcheck
  - name: github.com/alecthomas/gometalinter
  - name: golang.org/x/tools/cmd/gorename
